# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: main

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  generate-diagnostic-badges:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci --ignore-scripts

      - name: setup expo
        uses: expo/expo-github-action@v7
        with:
          # WARNING: don't use latest version of expo or eas
          expo-version: 6.1.0
          eas-version: 3.3.2
          token: ${{ secrets.EXPO_TOKEN }}

      - name: set badge messages
        run: |
          eas diagnostics | awk 'BEGIN {FS=": ";OFS=";"} {value=$2;if(length($2) > 0){if($2 ~ " - "){split($2,s," - ");value=s[1]} else if($2 ~ " => "){split($2,s," => ");value=s[2]};gsub(/ /,"",$1);gsub(/ /,"",value);if($1 !~ "OS") {print $1,value}}}' > /tmp/eas-diagnostics && \
            echo "BADGE_MSG_NODE=$(awk 'BEGIN {FS=";"} {if($1 == "Node"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV && \
            echo "BADGE_MSG_REACT=$(awk 'BEGIN {FS=";"} {if($1 == "react"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV && \
            echo "BADGE_MSG_REACT_NATIVE=$(awk 'BEGIN {FS=";"} {if($1 == "react-native"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV && \
            echo "BADGE_MSG_EXPO=$(awk 'BEGIN {FS=";"} {if($1 == "expo"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV && \
            echo "BADGE_MSG_EXPO_CLI=$(awk 'BEGIN {FS=";"} {if($1 == "expo-cli"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV && \
            echo "BADGE_MSG_EAS_CLI=$(awk 'BEGIN {FS=";"} {if($1 == "eas-cli"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV

      - name: generate node version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: ff849ae613ba3eb9f33fd95489070769
          filename: my-personal-finance_main_node-version.json
          label: node
          message: ${{ env.BADGE_MSG_NODE }}
          color: blue
          namedLogo: Node.js
          logoColor: white

      - name: generate node version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 52fe7006560c08ec53b2c7591abebb02
          filename: my-personal-finance_dev_node-version.json
          label: node
          message: ${{ env.BADGE_MSG_NODE }}
          color: blue
          namedLogo: Node.js
          logoColor: white

      - name: generate react version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 0d433553975c4d5b7e2650958dd29954
          filename: my-personal-finance_main_react-version.json
          label: react
          message: ${{ env.BADGE_MSG_REACT }}
          color: blue
          namedLogo: React
          logoColor: white

      - name: generate react version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 517beb7821f6a4216bb842911b7988f8
          filename: my-personal-finance_dev_react-version.json
          label: react
          message: ${{ env.BADGE_MSG_REACT }}
          color: blue
          namedLogo: React
          logoColor: white

      - name: generate react-native version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 77e7941867477ea7eb41385fbc1b3ff8
          filename: my-personal-finance_main_react-native-version.json
          label: react-native
          message: ${{ env.BADGE_MSG_REACT_NATIVE }}
          color: blue
          namedLogo: React
          logoColor: white

      - name: generate react-native version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 499ef2f2721f0fe3fdba27b3b7230f74
          filename: my-personal-finance_dev_react-native-version.json
          label: react-native
          message: ${{ env.BADGE_MSG_REACT_NATIVE }}
          color: blue
          namedLogo: React
          logoColor: white

      - name: generate expo-sdk version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: da18ded19f270754fda6e272690f87c1
          filename: my-personal-finance_main_expo-version.json
          label: expo-sdk
          message: ${{ env.BADGE_MSG_EXPO }}
          color: blue
          namedLogo: Expo
          logoColor: white

      - name: generate expo-sdk version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: b1f332f5f0782a2689ab314b61e32666
          filename: my-personal-finance_dev_expo-version.json
          label: expo-sdk
          message: ${{ env.BADGE_MSG_EXPO }}
          color: blue
          namedLogo: Expo
          logoColor: white

      - name: generate coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: dae55d347f3d6eea47576b298d2725c3
          filename: my-personal-finance_main_coverage.json
          label: coverage
          message: 0%
          color: red
          namedLogo: Jest
          logoColor: white

      - name: generate coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 388b37a300667c1a70c1d44a85a6228c
          filename: my-personal-finance_dev_coverage.json
          label: coverage
          message: 0%
          color: red
          namedLogo: Jest
          logoColor: white

  test:
    runs-on: ubuntu-latest
    needs: [generate-diagnostic-badges]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci --ignore-scripts

      - name: setup expo
        uses: expo/expo-github-action@v7
        with:
          # WARNING: don't use latest version of expo or eas
          expo-version: 6.1.0
          eas-version: 3.3.2
          token: ${{ secrets.EXPO_TOKEN }}

      - name: test
        # https://github.com/facebook/jest/issues/9324
        run: npm test -- --coverage

      - name: process coverage results
        run: |
          echo "BADGE_MSG_COVERAGE=$(npx ts-node ./scripts/cov-badge-helper.ts ./coverage/coverage-summary.json | awk 'BEGIN {FS=";"}{print $1}')" >> $GITHUB_ENV && \
            echo "BADGE_COLOR_COVERAGE=$(npx ts-node ./scripts/cov-badge-helper.ts ./coverage/coverage-summary.json | awk 'BEGIN {FS=";"}{print $2}' )" >> $GITHUB_ENV

      - name: generate coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: dae55d347f3d6eea47576b298d2725c3
          filename: my-personal-finance_main_coverage.json
          label: coverage
          message: ${{ env.BADGE_MSG_COVERAGE }}%
          color: ${{ env.BADGE_COLOR_COVERAGE }}
          namedLogo: Jest
          logoColor: white

      - name: generate coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 388b37a300667c1a70c1d44a85a6228c
          filename: my-personal-finance_dev_coverage.json
          label: coverage
          message: ${{ env.BADGE_MSG_COVERAGE }}%
          color: ${{ env.BADGE_COLOR_COVERAGE }}
          namedLogo: Jest
          logoColor: white

  publish:
    runs-on: ubuntu-latest
    environment: 'eas-update'
    needs: [test]

    steps:
      - name: check for EXPO_TOKEN
        run: |
            if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
              echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
              exit 1
            fi

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci --ignore-scripts

      - name: setup expo
        uses: expo/expo-github-action@v7
        with:
          # WARNING: don't use latest version of expo or eas
          expo-version: 6.1.0
          eas-version: 3.3.2
          token: ${{ secrets.EXPO_TOKEN }}

      - name: publish update
        run: eas update --auto --non-interactive
