# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      - name: test
        # https://github.com/facebook/jest/issues/9324
        run: npm test -- --ci --maxWorkers=2 --silent
